package furqon.io.github.mobilproject;

public class QuranMap {
    public static final int [] AYAHCOUNT = {
            7	,
            286	,
            200	,
            176	,
            120	,
            165	,
            206	,
            75	,
            129	,
            109	,
            123	,
            111	,
            43	,
            52	,
            99	,
            128	,
            111	,
            110	,
            98	,
            135	,
            112	,
            78	,
            118	,
            64	,
            77	,
            227	,
            93	,
            88	,
            69	,
            60	,
            34	,
            30	,
            73	,
            54	,
            45	,
            83	,
            182	,
            88	,
            75	,
            85	,
            54	,
            53	,
            89	,
            59	,
            37	,
            35	,
            38	,
            29	,
            18	,
            45	,
            60	,
            49	,
            62	,
            55	,
            78	,
            96	,
            29	,
            22	,
            24	,
            13	,
            14	,
            11	,
            11	,
            18	,
            12	,
            12	,
            30	,
            52	,
            52	,
            44	,
            28	,
            28	,
            20	,
            56	,
            40	,
            31	,
            50	,
            40	,
            46	,
            42	,
            29	,
            19	,
            36	,
            25	,
            22	,
            17	,
            19	,
            26	,
            30	,
            20	,
            15	,
            21	,
            11	,
            8	,
            8	,
            19	,
            5	,
            8	,
            8	,
            11	,
            11	,
            8	,
            3	,
            9	,
            5	,
            4	,
            7	,
            3	,
            6	,
            3	,
            5	,
            4	,
            5	,
            6

    };
    
    public static final String[] SURAHNAMES ={
            "Al-Faatiha",
            "Al-Baqara",
            "Al-Imraan",
            "An-Nisa",
            "Al-Maa-ida",
            "Al-Anaam",
            "Al-Araaf",
            "Al-Anfaal",
            "At-Tauba",
            "Yunus",
            "Hud",
            "Yusuf",
            "Ar-Rad",
            "Ibrahim",
            "Al-Hijr",
            "Al-Nahl",
            "Al-Israa",
            "Al-Kahf",
            "Maryam",
            "Taha",
            "Al-Anbiya",
            "Al-Hajj",
            "Al-Muminuun",
            "An-Nuur",
            "Al-Furqaan",
            "Ash-Shuaraa",
            "An-Naml",
            "Al-Qasas",
            "Al-Ankabut",
            "Ar-Ruum",
            "Luqman",
            "As-Sajdah",
            "Al-Ahzaab",
            "Saba",
            "Faatir",
            "Yaa Sin",
            "As-Saaffaat",
            "Saad",
            "Az-Zumar",
            "Ghaafir",
            "Fussilat",
            "Ash-Shuura",
            "Az-Zukhruf",
            "Ad-Dukhaan",
            "Al-Jaathiyah",
            "Al-Ahqaaf",
            "Muhammad",
            "Al-Fath",
            "Al-Hujuraat",
            "Qaaf",
            "Az-Zaariyaat",
            "At-Tuur",
            "An-Najm",
            "Al-Qamar",
            "Ar-Rahmaan",
            "Al-Waaqiah",
            "Al-Hadid",
            "Al-Mujaadalah",
            "Al-Hasyr",
            "Al-Mumtahanah",
            "As-Saff",
            "Al-Jumuah",
            "Al-Munaafiquun",
            "At-Taghaabun",
            "At-Talaaq",
            "At-Tahrim",
            "Al-Mulk",
            "Al-Qalam",
            "Al-Haaqqah",
            "Al-Maarij",
            "Nuh",
            "Al-Jinn",
            "Al-Muzzammil",
            "Al-Muddaththir",
            "Al-Qiaamah",
            "Al-Insaan",
            "Al-Mursalaat",
            "An-Naba",
            "An-Naaziaat",
            "Abasa",
            "At-Takwir",
            "Al-Infitaar",
            "Al-Mutaffifin",
            "Al-Inshiqaaq",
            "Al-Buruuj",
            "At-Taariq",
            "Al-Alaa",
            "Al-Ghaashiyah",
            "Al-Fajr",
            "Al-Balad",
            "Ash-Shams",
            "Al-Lail",
            "Adh-Dhuha",
            "Ash-Sharh",
            "At-Tiin",
            "Al-Alaq",
            "Al-Qadr",
            "Al-Bayyinah",
            "Az-Zalzalah",
            "Al-Aadiyaat",
            "Al-Qaariah",
            "At-Takaathur",
            "Al-Asr",
            "Al-Humazah",
            "Al-Fiil",
            "Quraisy",
            "Al-Maa'uun",
            "Al-Kauthar",
            "Al-Kaafiruun",
            "An-Nasr",
            "Al-Masad",
            "Al-Ikhlaas",
            "Al-Falaq",
            "An-Naas"      
    };

    public static int GetSurahLength(int i){
        try{
            return AYAHCOUNT[i];
        }catch (ArrayIndexOutOfBoundsException aiobx){
            return 0;
        }
    }

    public static final int[] REVELATION_ORDER = {

    };
}
